name: Java CI

on:
  push:
    branches: [ master ]

jobs:

  autotesting:
    runs-on: ubuntu-latest
    steps:

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cloning the repository
        uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew test

  code_format:
    runs-on: ubuntu-latest
    needs: [ autotesting ]
    steps:

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cloning the repository
        uses: actions/checkout@v3

      - name: Format the java code
        run: ./gradlew goJF

      - name: Apply formatted code to branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
          author_name: 'automatic_formatter[bot]'
          message: 'automatic codestyle format: ${date}'

  notification:
    runs-on: ubuntu-latest
    needs: [ code_format ]
    steps:

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECRET }}
          SLACK_USERNAME: Updates Notifier
          SLACK_TITLE: 'Main repository update'